install.packages("dplyr")
library(dplyr)
iris%>%head(n=4)
iris3PrimerasColumnas<-iris%>%select(Sepal.Length, Sepal.Width, Petal.Length)
#View(iris3PrimerasColumnas) esto es para ver en forma tabla tipo excel
irisSinPetalwidth<-iris%>%select(-Petal.Width)
#View(irisSinPetalwidth)
irisOnlyStartWithP<-iris%>%select(starts_with("P"))
#View(irisOnlyStartWithP)
irisFiltrado<-iris%>%filter(Sepal.Length>=4.6,Petal.Width>=0.5)
#View(irisFiltrado)
irisSelectSepalWandL<-iris%>%select(Sepal.Width,Sepal.Length)
#View(irisSelectSepalWandL)
irisArrangeWithSepalW<-iris%>%arrange(Sepal.Width)
#View(irisArrangeWithSepalW)
irisSelect<-iris%>%select(Sepal.Length,Sepal.Width,Petal.Length)%>%arrange(Sepal.Length,Sepal.Width)
#View(irisSelect)
